using LogScraper.Utilities.Extensions;

namespace LogScraper.LogPostProcessors
{
    /// <summary>
    /// Represents the result of post-processing a log entry, including the processor type and the processed log text.
    /// </summary>
    /// <param name="processorKind">The kind of post-processor applied to the log entry. Determines how the log text was processed.</param>
    /// <param name="processedText">The log entry text after post-processing has been applied. Cannot be null.</param>
    public class LogPostProcessResult(LogPostProcessorKind processorKind, string processedText)
    {
        /// <summary>
        /// Gets the kind of log post processor associated with this instance.
        /// </summary>
        public LogPostProcessorKind ProcessorKind { get; } = processorKind;
        /// <summary>
        /// Gets the processed text generated by the operation.
        /// </summary>
        public string ProcessedText { get; } = processedText;
        /// <summary>
        /// Gets the number of lines in the processed text.
        /// </summary>
        public int LineCount { get; } = processedText.CountLines();
    }
}
